# Generated by Django 3.1.3 on 2020-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_of_blog',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
