# Generated by Django 3.1.3 on 2020-11-21 22:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201121_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_of_blog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
