# Generated by Django 3.1.3 on 2020-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201216_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfolio',
            name='modal_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='modal_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='porfolio',
            name='short_desc',
            field=models.CharField(default='', max_length=128),
        ),
    ]
